function createfigure8(xdata1, ydata1, zdata1, X1, Y1, Z1)
%CREATEFIGURE(xdata1, ydata1, zdata1, X1, Y1, Z1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata
%  X1:  vector of x data
%  Y1:  vector of y data
%  Z1:  vector of z data

%  Auto-generated by MATLAB on 06-Oct-2021 20:52:13

% Create figure
figure('InvertHardcopy','off','PaperSize',[20.99999864 29.69999902],...
    'Color',[1 1 1]);

% Create axes
axes1 = axes('Position',...
    [0.0749791646798452 0.101981665839581 0.703021010160446 0.882583088476085]);
hold(axes1,'on');

% Create surf
surf(xdata1,ydata1,zdata1);

% Create plot3
plot31 = plot3(X1,Y1,Z1,'LineWidth',3,'Color',[1 0 0]);

% The following line demonstrates an alternative way to create a data tip.
% datatip(plot31,1,100,100);
% Create datatip
datatip(plot31,'DataIndex',10,'Location','northeast');

% Create zlabel
zlabel('Energy transfer, % of energy transfer at AAF=1 p.u.');

% Create ylabel
ylabel('Life,% of designed life');

% Create xlabel
xlabel('Ageing limit (AAF), p.u.');

view(axes1,[-27.9388768898488 36.0699438202247]);
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',16);
% Create colorbar
colorbar(axes1,'Position',...
    [0.807166841506958 0.101981665839581 0.0166666666666667 0.889455800881226]);

